name: Build & Release

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node: ["22.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build
